Awandersleben05/bxc 82 ide global variable creation
BX-Coding/pyatch-react-ide pull request #14
Opened 2023-05-17 15:15 UTC by Snoopy219

I fixed the alignment issues.

2023-05-17 15:31 UTC, Snoopy219 commented
<img width="1803" alt="Screenshot 2023-05-17 at 11 30 14 AM" src="https://github.com/BX-Coding/pyatch-react-ide/assets/78870469/5b628db0-124b-4b1d-a5e6-bb55ea1c53e9">

2023-05-17 15:55 UTC, ElliotRoe requested changes
<img width="1504" alt="Screen Shot 2023-05-17 at 11 37 28 AM" src="https://github.com/BX-Coding/pyatch-react-ide/assets/32718462/2098dd85-d6c2-4c68-958e-5d824360f8f9">

Very good work!!! I commented on a couple of minor changes about variable file location and mui best practices. I also included a screenshot of some minor graphical changes. Please ping dev if anything's unclear.

2023-05-17 15:59 UTC, ElliotRoe commented
Also, forgot to mention in the review, currently GitHub is not able to automatically merge your changes into main. To fix this, please merge main into your branch and resolve any conflicts. Then after this go ahead and push your changes and it should be able to automatically merge.
The command to merge main into your branch is:
`git merge main/origin`

2023-05-18 15:54 UTC, ElliotRoe approved these changes

2023-05-18 15:54 UTC, merged